### ISSUE TITLE
Cannot delete master branch in updated GitHub application

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-coming-soon#1]
@thomasjbradley

Hello, I've just updated my github application and I cannot find the option to delete the master branch. I have already created gh-pages and set it as the default branch. If possible could I have a screen shot of the area where this feature is located in the updated application?

thanks.

**Comment by thomasjbradley** [comment]
I actually don't think its possible to delete master anymore. At least not in a consistent way. I was able to delete it once on one person's computer but could never get it to work again.

**Comment by valeriebordeleau** [comment]
I seemed to be able to delete it. Github says I only have one branch now. However it's quite annoying because I didn't realize I had the master branch selected and was accidentally working within it for a couple commits.
![screen shot 2015-09-11 at 11 13 58 am](https://cloud.githubusercontent.com/assets/6373198/9818425/85514ca4-5876-11e5-8717-8c9a0db66000.png)
