### ISSUE TITLE
Cannot remove padding around background image

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-coming-soon#2]
@thomasjbradley

I am not sure which element is causing there to be padding on my background image. I made sure there was no padding/margins on html, and I don't believe gutter is applied to anything. Thanks.

<div class="unit unit-xs-1 unit-s-1 unit-m-1-2 unit-l-1-2 push-0">
       <div class="image"></div>

 </div>

.image {
    background-image: url(../artwork/photo.jpg);
    height: 500px;
    background-position: center center;
}

**Comment by thomasjbradley** [comment]
Check if the `body` has `margin` or `padding` on it.

**Comment by valeriebordeleau** [comment]
Perfect. Thank-you.
