### ISSUE TITLE
Animation doesn't work in all browsers

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-coming-soon#3]
@thomasjbradley 

The colour change on my social media icons does not slowly transition on chrome like it does in firefox. Anything I am missing/ mistakes? thanks.

.st0:hover{
    fill:#ACC6C9;
    -webkit-transition: all 400ms ease-out; 
    transition: all 400ms ease-out;
    }

**Comment by thomasjbradley** [comment]
Try puttting the transitions on the default state, not on the `:hover`.

**Comment by valeriebordeleau** [comment]
This maybe unrelated but the font-weight is also heavier in chrome.

**Comment by thomasjbradley** [comment]
Font-weight is unpredictable across browsers; they all render type differently.

**Comment by valeriebordeleau** [comment]
It seems strange because it grabbed Open Sans from Google fonts, but didn't get the proper weight. 

The transition is fine in chrome & firefox, just not safari at the moment.

**Comment by thomasjbradley** [comment]
What version of Safari are you using? I have Safari/8.0.8 and the transition is all good.

**Comment by valeriebordeleau** [comment]
7.1.8 

Time for an update. Should I still try to fix it for older browsers?

**Comment by thomasjbradley** [comment]
If it's only the transition that isn't working I would ignore it. Transitions are privilege: they aren't necessary to use the website.

**Comment by valeriebordeleau** [comment]
Okay. Awesome thanks. I'll definitely update so I don't run into this issue again.
