### ISSUE TITLE
Social Media icons in M/L screens 

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/portfolio-coming-soon#4]
@thomasjbradley
Social Media icons in M/L screens should be side by side not stacked. I'm not sure why they are being pushed to the next line as the code is identical to that of the code on the S/M screens which is working properly. thx.

**Comment by thomasjbradley** [comment]
It looks like it's because of the `.disappear-sm` class, when I remove it the problem is fixed.
Maybe try putting the `.grid` into another `<div>` and put the class onto it instead.

**Comment by valeriebordeleau** [comment]
thanks. that seems to have fixed it. It removed some padding in the process but that should be an easy fix.
